# Generated by Django 6.0 on 2026-01-06 03:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_quizmodel_total_questions_enrollmentmodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresultmodel',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='results', to='core.quizmodel'),
        ),
        migrations.AddField(
            model_name='quizresultmodel',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterUniqueTogether(
            name='quizresultmodel',
            unique_together={('user', 'quiz')},
        ),
    ]
