# Generated by Django 6.0 on 2026-01-06 10:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_quizresultmodel_quiz_quizresultmodel_score_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemodel',
            name='is_paid',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='coursemodel',
            name='price',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
    ]
