# Generated by Django 6.0 on 2026-01-06 10:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_coursemodel_is_paid_alter_coursemodel_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursemodel',
            name='is_paid',
        ),
        migrations.AddField(
            model_name='enrollmentmodel',
            name='is_paid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
