# Generated by Django 6.0 on 2026-01-07 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_quizmodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizmodel',
            name='user',
        ),
    ]
