# Generated by Django 6.0 on 2026-01-07 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_quizmodel_quiz_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizresultmodel',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='core.quizmodel'),
        ),
    ]
